"""segundo schema

Revision ID: 2da3a2927d6d
Revises: 2133026af58e
Create Date: 2025-10-16 15:50:31.976096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2da3a2927d6d'
down_revision: Union[str, Sequence[str], None] = '2133026af58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('participant_document_id', sa.String(length=20), nullable=True),
    sa.Column('registered_by_staff_id', sa.Integer(), nullable=True),
    sa.Column('qr_code_sent', sa.Boolean(), nullable=True),
    sa.Column('qr_sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('registration_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['participant_document_id'], ['participants.document_id'], ),
    sa.ForeignKeyConstraint(['registered_by_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('entry_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('exit_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('scanned_by_staff_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.id'], ),
    sa.ForeignKeyConstraint(['scanned_by_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('staff', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table('attendances')
    op.drop_table('event_registrations')
    # ### end Alembic commands ###
