"""cuarto schema

Revision ID: 45d63c90231f
Revises: 89a774ee2839
Create Date: 2025-10-16 16:25:37.791856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45d63c90231f'
down_revision: Union[str, Sequence[str], None] = '89a774ee2839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'idnumber',
               existing_type=mysql.SMALLINT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'idnumber',
               existing_type=sa.String(length=20),
               type_=mysql.SMALLINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
