"""Ajuste de asistencia

Revision ID: 609766a14aa4
Revises: a3d24dc25213
Create Date: 2025-10-16 19:28:34.270567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '609766a14aa4'
down_revision: Union[str, Sequence[str], None] = 'a3d24dc25213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('participant_document_id', sa.String(length=50), nullable=False))
    op.add_column('attendances', sa.Column('event_id', sa.Integer(), nullable=False))
    op.add_column('attendances', sa.Column('check_in_time', sa.DateTime(), nullable=True))
    op.add_column('attendances', sa.Column('check_out_time', sa.DateTime(), nullable=True))
    op.add_column('attendances', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('attendances', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.alter_column('attendances', 'registration_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.drop_constraint(op.f('attendances_ibfk_2'), 'attendances', type_='foreignkey')
    op.create_foreign_key(None, 'attendances', 'staff', ['verified_by'], ['id'])
    op.create_foreign_key(None, 'attendances', 'events', ['event_id'], ['id'])
    op.drop_column('attendances', 'created_at')
    op.drop_column('attendances', 'exit_timestamp')
    op.drop_column('attendances', 'scanned_by_staff_id')
    op.drop_column('attendances', 'entry_timestamp')
    op.drop_column('attendances', 'session_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('session_number', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('entry_timestamp', mysql.TIMESTAMP(), nullable=True))
    op.add_column('attendances', sa.Column('scanned_by_staff_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('exit_timestamp', mysql.TIMESTAMP(), nullable=True))
    op.add_column('attendances', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True))
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.create_foreign_key(op.f('attendances_ibfk_2'), 'attendances', 'staff', ['scanned_by_staff_id'], ['id'])
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.alter_column('attendances', 'registration_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('attendances', 'verified_by')
    op.drop_column('attendances', 'status')
    op.drop_column('attendances', 'check_out_time')
    op.drop_column('attendances', 'check_in_time')
    op.drop_column('attendances', 'event_id')
    op.drop_column('attendances', 'participant_document_id')
    # ### end Alembic commands ###
