"""tercer schema

Revision ID: 89a774ee2839
Revises: 2da3a2927d6d
Create Date: 2025-10-16 16:21:59.268492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89a774ee2839'
down_revision: Union[str, Sequence[str], None] = '2da3a2927d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('idnumber', sa.SmallInteger(), nullable=True))
    op.drop_column('participants', 'semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('semester', mysql.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('participants', 'idnumber')
    # ### end Alembic commands ###
