"""Add is_paid to event_registrations

Revision ID: a3d24dc25213
Revises: b98893643c00
Create Date: 2025-10-16 16:36:01.300792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d24dc25213'
down_revision: Union[str, Sequence[str], None] = 'b98893643c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('is_paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_registrations', 'is_paid')
    # ### end Alembic commands ###
